# Schema for the configuration files of the Outline Entity module.

outline.settings:
  type: config_object
  label: 'Outline settings'
  mapping:
    maintain_index_table:
      type: boolean
      label: 'Maintain index table'

outline.outline.*:
  type: config_entity
  label: 'Outline'
  mapping:
    name:
      type: label
      label: 'Name'
    description:
      type: label
      label: 'Description'
    weight:
      type: integer
      label: 'Weight'
    render:
      type: string
      label: 'Render as'
    expand_levels:
      type: integer
      label: 'Expand levels'
    hide_name:
      type: boolean
      label: 'Hide name field'
    hide_site:
      type: boolean
      label: 'Hide site entry'
    oid:
      type: string
      label: 'Machine name'
    root_entry:
      type: string
      label: 'Root Entry'
    site_entry:
      type: string
      label: 'Site Entry'

field.formatter.settings.entity_reference_rss_category:
  type: mapping
  label: 'Outline format settings'
