<?php

/**
 * @file
 * Contains wikilex_media.module.
 */

use Drupal\wikilex_media\Entity\BaseMedia;
use Drupal\wikilex_media\MediaStorage;

/**
 * Implements hook_entity_extra_field_info().
 */
function wikilex_media_entity_extra_field_info() {
  $extra = [];

  foreach (MediaStorage::BUNDLE_CLASSES as $type => $class) {
    if (is_callable($class . '::getExtraFieldDefinitions')) {
      $extra['media'][$type] = $class::getExtraFieldDefinitions();
    }
  }

  return $extra;
}

/**
 * Implements hook_entity_type_alter().
 */
function wikilex_media_entity_type_alter(array &$entity_types) {
  if (isset($entity_types['media'])) {
    $entity_types['media']->setClass(BaseMedia::class);
    $entity_types['media']->setStorageClass(MediaStorage::class);
  }
}
