<?php
/**
 * @file
 * Theme functions for the media_entity module.
 */

use Drupal\Core\Render\Element;
use Drupal\Core\Url;
use Drupal\Component\Utility\Html;

///**
// * Prepares variables for outline templates.
// *
// * Default template: outline.html.twig.
// *
// * @param array $variables
// *   An associative array containing:
// *   - outline: An outline for display.
// */
//function template_preprocess_xoutline(&$variables) {
//
//  $outline = $variables['outline'];
//  $variables['name'] = $outline->label();
//  $variables['attributes']['class'][] = 'outline';
//
//}
  
  //kint($outline_tree);
  //$variables['attributes']['class'][] = Html::getClass('outline-' . $outline->bundle());
//   if (!$outline->isPublished()) {
//     $variables['attributes']['class'][] = 'unpublished';
//   }
//   if ($variables['elements']['#view_mode']) {
//     $variables['attributes']['class'][] = Html::getClass('view-mode-' . $variables['elements']['#view_mode']);
//   }
  // Helpful $content variable for templates.
//   foreach (Element::children($variables['elements']) as $key) {
//     $variables['content'][$key] = $variables['elements'][$key];
//   }

